### ISSUE TITLE
dreamer v3 resuming problem

### ISSUE THREAD

**Issue by Disastorm** [Eclectic-Sheep/sheeprl#273] opened 2024-04-26 08:49 UTC
i noticed something when resuming. When I had stopped my training initially the envs were getting like 1k-2k rewards, and now after resuming they are only getting around 700. Did they loose some training or something?

![image](https://github.com/Eclectic-Sheep/sheeprl/assets/1088694/a7bd1e4f-13ed-480a-950b-0729404ed2eb)

**Comment by Disastorm** [comment] 2024-04-26 08:53
Takes a few hours to get back to where i was before
![image](https://github.com/Eclectic-Sheep/sheeprl/assets/1088694/d9f983b6-472f-4cbe-bb6f-c1e5d24b9033)

**Comment by belerico** [comment] 2024-04-26 10:21
Hi @Disastorm, when you resume you should set the `learning_starts` or the `per_rank_pretrain_steps` accordingly.
There could be a case where you saved a checkpoint at steps N and then you stopped the training at step N+M. In this case you have an old checkpoint with the buffer that it's kept since it's memory mapped, therefore when you resume you have trajectories coming from a future policy. You should spend some time to train your agent a little bit to overcome this issue.
We never found a beautiful solution for this, but we're open to suggestions

**Comment by Disastorm** [comment] 2024-04-26 12:08
is it memory mapped? the buffer checkpoint is set to False?
Anyway if i adjust learning_starts is that basically similar to the steps it would do before training in the previous version? What would i set learning_starts to?
Also fyi i stopped the training at like 215k while the checkpoint was at 200k. I wasn't aware there was anything that carried over aside from the checkpoint file itself when choosing resume from. It did create a new memory map so i dont think it re-used the old one?

**Comment by belerico** [comment] 2024-04-26 16:31
Sorry, I haven't made myself clear in the previous post.

The behaviour that I mentioned happens if you chekpoint the buffer and the buffer is memory mapped. 

If you checkpoint your buffer without memory mapping nothing happens, cause you can safely resume your training as the buffer is saved within the checkpoint.

If you don't save your buffer in the checkpoint, then you would pre-fill the buffer with the policy (agent) from the checkpoint so to recreate some sort of history of the buffer before the experiment was stopped and that's what's happening: your agent will pre-fill the buffer for at maximum `old_learning_start` steps before resuming training.

Right now there's no way to pre-fill the buffer after resuming from checkpoint.
Am i right @michele-milesi?

**Comment by Disastorm** [comment] 2024-04-26 16:50
So there are 2 methods of checkpointing the buffer? The default seems to just have checkpoint disabled. But you are saying you can enable either a memory mapped version or a version that is stored inside the checkpoint?
And without the buffer, I know previously it used to do like 65k steps to prefil the buffer automatically, but I guess it doesnt do that now, so I should try to do something like for example if the checkpoint was at at 500k then I'd want to set training_starts to like 565k or something like that?

**Comment by belerico** [comment] 2024-04-26 17:06
> And without the buffer, I know previously it used to do like 65k steps to prefil the buffer automatically, but I guess it doesnt do that now, so I should try to do something like for example if the checkpoint was at at 500k then I'd want to set training_starts to like 565k or something like that?

This is already done. Suppose that you start an experiment with `learning_starts=65k` and you decide to not save the buffer in the checkpoint. Furthermore, suppose that you have a checkpoint at `500k`. When you resume your checkpoint your old hydra config (the one that was used to launch the experiment that was stopped) is read and merged with the new one (the one where you're resuming your training), this means that if you had a `learning_starts=65k` then your agent will do 65k pre-fill steps of the buffer, so your resumed agent will start to train at 565k. If you want to increase the `learning_starts`, as a workaround you should increase that value from the hydra `config.yaml` of your stopped experiment

> But you are saying you can enable either a memory mapped version or a version that is stored inside the checkpoint?

Yes, with `buffer.memmap=True` which is the default in the `configs/exp/dreamer_v3.yaml` config. In this case only the reference to the file is saved inside the checkpoint. so that when you resume we read that reference and the buffer is ready to go (with the issue that i explained in the previous-previous post)

**Comment by michele-milesi** [comment] 2024-04-27 07:20
Hi there,

> Right now there's no way to pre-fill the buffer after resuming from checkpoint.
> Am i right @michele-milesi?

So far, the buffer is pre filled only when you do not save the buffer in the checkpoint (with and without memory mapping).

@belerico we should add a config for choosing whether or not to prefill the buffer when resuming the checkpoint. 
It is a useful thing that we have experienced with our experiments.

**Comment by Disastorm** [comment] 2024-04-27 09:17
I set learning starts to 65k but its still not prefilling, or at least it doesnt seem like it is because its slow from the beginning ( it used to be when it did the prefilling it was super fast ).

**Comment by Disastorm** [comment] 2024-04-27 09:58
ok i think it worked now when i put memmap false

**Comment by Disastorm** [comment] 2024-04-27 10:16
actually its weird it started out good then got worse?

![image](https://github.com/Eclectic-Sheep/sheeprl/assets/1088694/ae867824-b467-4fe8-8737-e9b0f05f8099)

**Comment by belerico** [comment] 2024-04-27 11:07
Hi @Disastorm, can you specify exactly what you have done? Maybe share your config for the first training and the one for the resuming.
Thanks

**Comment by Disastorm** [comment] 2024-04-27 11:20
I used default dreamer v3 large and changed replay_ratio to 0.2 for initial training.
For resuming I just added the resume_from in the checkpoint.

That resulted in my initial post, basically it lost a whole bunch of training, my current model will drop from 2k rewards down to 700 or something, so it will lose like multiple hours of training.

Then I set learning_starts to 66k and it still didn't help anything.
then i set memmap false and i got the image you see in my previous comment.

**Comment by Disastorm** [comment] 2024-04-27 11:24
I think I remember before you had some issue with windows that you fixed, is it possible your new dreamerv3 has another issue with windows?

**Comment by belerico** [comment] 2024-04-27 15:50
I've prepared [here](https://github.com/Eclectic-Sheep/sheeprl/tree/feature/resume-pre-fill) a branch where you can decide how many policy steps you want to perform after resuming from the checkpoint. You can specify `algo.learning_starts=N`. Bear in mind that **N is divided by the `num_envs * world_size`, i.e. by the policy_steps**. This means that if you have M parallel envs and K processes (multi-gpu for example) then `learning_starts = learning_starts // (M * K)`. We will fix this so the user can specify the `learning_starts` in policy steps

**Comment by Disastorm** [comment] 2024-04-27 17:16
Have the definitions of buffer.checkpoint and buffer.memmap changed?
I think back during this issue https://github.com/Eclectic-Sheep/sheeprl/issues/188

buffer.checkpoint basically meant each run was going to use the same memmap files from one of the previous runs, the actual same file in the same folder from the older run, so that it didnt create new memmap files for each run.
I don't actually know what buffer.memmap did as I just always had it on.

but it sounds like you are saying now buffer.checkpoint now stores the buffer in the checkpoint file, and buffer.memmap does what buffer.checkpoint used to do, or something like that?

I can go ahead and try your branch, too, but just wondering why is the learning_starts divided by num env?

**Comment by belerico** [comment] 2024-04-27 17:51
> Have the definitions of buffer.checkpoint and buffer.memmap changed?
I think back during this issue https://github.com/Eclectic-Sheep/sheeprl/issues/188

Nothing changed from there that I know of

> buffer.checkpoint basically meant each run was going to use the same memmap files from one of the previous runs, the actual same file in the same folder from the older run, so that it didnt create new memmap files for each run. The only thing in the checkpoint was just the path to the files.

This is just what's happening now

 > but it sounds like you are saying now buffer.checkpoint now stores the buffer in the checkpoint file, and buffer.memmap does what buffer.checkpoint used to do, or something like that?

This is not what i'm saying. What i wrote to you are the different scenarios that you could encounter.

> I can go ahead and try your branch, too, but just wondering why is the learning_starts divided by num env?

Because we need to convert those steps into [policy-steps](https://github.com/Eclectic-Sheep/sheeprl/blob/main/howto/work_with_steps.md)

**Comment by Disastorm** [comment] 2024-04-28 05:09
I see you are right your descriptions are actually the same, thanks. The steps that print out while training, are those the env steps or the policy steps?

**Comment by belerico** [comment] 2024-04-28 08:02
Those are policy steps

**Comment by Disastorm** [comment] 2024-04-28 08:19
It looks like in your branch, learning starts is already in policy steps. i just tested with 100k and it started trying to learn after 100k policy steps. However, it got this error:
```
...
File "H:\aiWorkspace\gymRetro\rl\sheeprl\sheeprl\sheeprl\data\buffers.py", line 686, in <listcomp>
    b.sample(
  File "H:\aiWorkspace\gymRetro\rl\sheeprl\sheeprl\sheeprl\data\buffers.py", line 463, in sample
    return self._get_samples(
  File "H:\aiWorkspace\gymRetro\rl\sheeprl\sheeprl\sheeprl\data\buffers.py", line 497, in _get_samples
    flattened_v = np.take(np.reshape(v, (-1, *v.shape[2:])), flattened_idxes, axis=0)
  File "<__array_function__ internals>", line 180, in take
  File "C:\Users\Disastorm\MiniConda3\envs\sheeprl\lib\site-packages\numpy\core\fromnumeric.py", line 190, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "C:\Users\Disastorm\MiniConda3\envs\sheeprl\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 73.2 GiB for an array with shape (6400320, 3, 64, 64) and data type uint8
```

**Comment by belerico** [comment] 2024-04-28 10:26
> It looks like in your branch, learning starts is already in policy steps. i just tested with 100k and it started trying to learn after 100k policy steps.

It only happens if you're using 1 parallel env and 1 process (1 GPU for example), as you can see [here](https://github.com/Eclectic-Sheep/sheeprl/blob/77a68fd37096d910c25403da5a79371bd8d8ef18/sheeprl/algos/dreamer_v3/dreamer_v3.py#L507).

> However, it got this error:
```
...
File "H:\aiWorkspace\gymRetro\rl\sheeprl\sheeprl\sheeprl\data\buffers.py", line 686, in <listcomp>
    b.sample(
  File "H:\aiWorkspace\gymRetro\rl\sheeprl\sheeprl\sheeprl\data\buffers.py", line 463, in sample
    return self._get_samples(
  File "H:\aiWorkspace\gymRetro\rl\sheeprl\sheeprl\sheeprl\data\buffers.py", line 497, in _get_samples
    flattened_v = np.take(np.reshape(v, (-1, *v.shape[2:])), flattened_idxes, axis=0)
  File "<__array_function__ internals>", line 180, in take
  File "C:\Users\Disastorm\MiniConda3\envs\sheeprl\lib\site-packages\numpy\core\fromnumeric.py", line 190, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "C:\Users\Disastorm\MiniConda3\envs\sheeprl\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 73.2 GiB for an array with shape (6400320, 3, 64, 64) and data type uint8
```

If you don't memmap your buffer and you don't have 80GB of RAM on your PC how is it possible to allocate that amount of RAM to hold all the images? We pre-allocate everything in the buffer because sooner or later you need to have that amount of data residing in the RAM

**Comment by Disastorm** [comment] 2024-04-28 10:30
Sorry didnt mention I set memmap back to true.
This is the buffer settings from the same run that gave me the above error:
![image](https://github.com/Eclectic-Sheep/sheeprl/assets/1088694/62935b69-2631-401e-b2e8-47d305d583d7)

**Comment by belerico** [comment] 2024-04-28 11:27
Yeah, you're right about the learning starts: I got confused! Those are transformed to policy steps as in the link that I shared.

Acknowledging that, have you solved your issue about the resuming? What is your issue now? If this regards some memory issue i suggest you to open another issue

**Comment by Disastorm** [comment] 2024-04-28 11:37
Yes I get that memory issue you saw before, however this is only happened when i did the last attempt which used your branch. I have never seen this error before on the main branch.

**Comment by belerico** [comment] 2024-04-28 12:37
I've spotted the memory error. The problem is related to the replay-ratio: since the replay-ratio is the number of gradient steps per policy steps (i.e. a replay-ratio=0.5 means 1 gradient steps every 2 policy steps), when we resume from the checkpoint the raply-ratio loads its state and when you set the learning_starts to something > 0 then the first time the learning starts the Ratio class wants to keep maintaining the ratio, that's why you see it's slower when training the first time after resuming and that's also the cause of the memory error, since we sample all the needed trajectories once a loop through them. In the branch it should now be fixed the memory error.
Can you confirm this?

**Comment by Disastorm** [comment] 2024-04-28 13:37
looks like it got past the memory error, i see my gpu vram usage went up and my gpu is processing stuff, although i havn't seen a policy_step reward log after the prefill yet, even though its been over 30 minutes which is very strange. Do you have any ideas about this? Pretty sure the policy step logs should be showing up in like 5 or at least 10 minutes normally.

**Comment by Disastorm** [comment] 2024-04-28 13:53
still no logs at all, no further checkpoints have been created either so i think somethings wrong with the training portion even though it passed the memory error, although ill keep it on for a total of an hour before i cancel it

**Comment by belerico** [comment] 2024-04-28 14:35
> looks like it got past the memory error, i see my gpu vram usage went up and my gpu is processing stuff, although i havn't seen a policy_step reward log after the prefill yet, even though its been almost 30 minutes which is very strange. Do you have any ideas about this?

As i told you in the previous answer the slowdown you see is due to the replay ratio. Suppose for example the following:

* replay_ratio=0.5 (globally, 1 training step every 2 policy steps)
* num_envs = 1
* You have done 4000 policy steps at your last checkpoint
* When you resume you set the learning_starts=2048

When you resume your training the [Ratio](https://github.com/Eclectic-Sheep/sheeprl/blob/2bae37985d789a67d569bf37ed937b9445ae9ab8/sheeprl/utils/utils.py#L261) class knows that 4000 steps have already been done so far. Now, you want to do 2048 pre-fill steps and to maintain the replay-ratio at 0.5 the Ratio class will return a number of training step equal to (6048-4000) * 0.5 = 2048 * 0.5 = 1024. This means that the first time you resume, **to maintain the replay-ratio**, you will do 1024 training steps. That's why you see a slowdown.
Is this answer your doubts?

**Comment by Disastorm** [comment] 2024-04-28 14:38
Sorry I don't really understand the details, Is there a way I can get it to train at the normal speed instead of like 10 or 20 times slower that I guess it might be doing?

**Comment by belerico** [comment] 2024-04-28 14:52
From the new branch, set `learning_starts=0`

**Comment by belerico** [comment] 2024-04-28 14:55
https://meet.google.com/ayv-zxje-vjt

**Comment by belerico** [comment] 2024-04-28 14:58
From [this](https://github.com/Eclectic-Sheep/sheeprl/tree/feature/resume-pre-fill) branch can you try to set `learning_starts=0` after resuming?

**Comment by belerico** [comment] 2024-04-28 15:22
This is an experiment i've done with the new branch:

![image](https://github.com/Eclectic-Sheep/sheeprl/assets/18405289/1f8e2121-80bd-483f-871b-7a2f9e6cd2c6)

I've run a training with the following config:

```bash
python sheeprl.py exp=dreamer_v3 \                   
env=gym env.id=CartPole-v1 \
env.num_envs=4 \
fabric.accelerator=gpu \
fabric.precision=16-mixed \
algo=dreamer_v3_S \
algo.learning_starts=1024 \
algo.cnn_keys.encoder=\[\] \
algo.mlp_keys.encoder=\["vector"\] \
algo.cnn_keys.decoder=\[\] \
algo.mlp_keys.decoder=\["vector"\] \
algo.per_rank_sequence_length=64 \
algo.replay_ratio=0.5 \
algo.world_model.decoupled_rssm=False \
algo.world_model.learnable_initial_recurrent_state=False
```

Then i've stoppend the training and resumed it with `learning_starts=0`, depicted in blue in the above figure.

Then i've stopped again the training and resumed it again with `learning_starts=0`, depicted in red in the above figure.

As you can see the training resumed perfectly!

**Comment by Disastorm** [comment] 2024-04-28 15:24
I'll try it but I"m just wondering how does the prefill work, does it automatically detect some amount to prefill even if you have it set to 0? You are using checkpoint false right?

**Comment by belerico** [comment] 2024-04-28 15:25
@Disastorm, please come in this [google meet](https://meet.google.com/ayv-zxje-vjt)

**Comment by Disastorm** [comment] 2024-04-28 15:45
@belerico I'll try out the stuff you mentioned in the meeting tommorow, sorry don't have the time right now to do it.

**Comment by Disastorm** [comment] 2024-04-29 14:36
@belerico  So the resuming with checkpoint: true and memmap: true does work as you've said although when checkpoint is disabled and pre-filling is attempted even with low learning_starts it always seems to be abnormally slow, so I've stopped trying to attempt that alternative. I'm just going to stick with the checkpoint: true and memmap: true.

**Comment by belerico** [comment] 2024-04-29 14:47
@michele-milesi we should decide what to do when we don't checkpoint the buffer and we need to prefill the buffer. The simplest thing is to disable the replay-ratio. Another solution is to dilute the pre-fill steps over the course of the agent training. What do you think?

**Comment by Disastorm** [comment] 2024-04-29 14:52
I dont really know about that so I can't really help. I guess forcing the replay-ratio to 1 could be an ok solution but it could be annoying if someone wants a different ratio, and theyll need to reconfigure how often they save a checkpoint and whatnot since the steps are going to be slower.

**Comment by michele-milesi** [comment] 2024-05-01 20:30
> @michele-milesi we should decide what to do when we don't checkpoint the buffer and we need to prefill the buffer. The simplest thing is to disable the replay-ratio. Another solution is to dilute the pre-fill steps over the course of the agent training.
> What do you think?

What if we pre-filled the dataset with the number of policy steps played at the time of the checkpoint and continued training as if nothing had happened? (during the pre-fill phase, we do not increase the policy steps).

For example, the experiment was interrupted at the `100_000` (policy) step, and the buffer was not saved into the checkpoint. When resuming the experiment, the agent plays `100_000` (policy) steps to pre-fill the dataset. When the pre-fill is done, the training is resumed from step `100_000`.

This way we would (more or less) have the same situation we had at the moment of the checkpoint, and the ratio would not be affected by the pre-fill.
Otherwise, as you say, we could dilute the pre-fill steps over the course of the agent training.

**Closed** 2024-05-09 07:14 UTC

**Comment by Xritsos** [comment] 2026-01-28 22:48
Hello there, in your experiment https://github.com/Eclectic-Sheep/sheeprl/issues/273#issuecomment-2081519124 you do not mention everything. I set memmap to False, checkpoint to True. The buffer size set to 1_500_000 and checkpoint every 20_000 steps. First the AsyncEnv throw an error. Then I set env.sync to True and when it reached the checkpoint step the process was killed. I have 24 GB VRAM and 128 GB RAM, what could be the issue?
